global:
  scrape_interval: 15s   #15秒采集一次
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  #监控服务
  - job_name: 'order'
    scrape_interval: 5s   #覆盖默认值
    static_configs:
      - targets: ['192.168.1.201:9092']

